Traceback (most recent call last):
  File "/home/cmput274/MorningProblems/decoder/soln/decoder.py", line 27, in <module>
    raise ValueError()
ValueError
